version: 2
aliases:
  - &install-xmlstarlet
    name: Install xmlstarlet from apt
    command: apt-get -y update && apt-get -y install xmlstarlet
jobs:
  build:
    docker:
      - image: maven:3.5.4-jdk-8
        cmd: ["/bin/bash"]
    environment:
      MAVEN_OPTS: -Xmx3G
    steps:
      - checkout
      - run: *install-xmlstarlet
      - restore_cache:
          key: dep-cache-{{ checksum "pom.xml" }}
      - run: mvn org.apache.maven.plugins:maven-dependency-plugin:3.1.0:go-offline -s .circleci/settings.xml
      - save_cache:
          paths:
            - ~/.m2
          key: dep-cache-{{ checksum "pom.xml" }}
      # Cannot use -o because of snapshot dependencies.
      - run: mvn install -s .circleci/settings.xml
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
  deploy:
    docker:
      - image: maven:3.5.4-jdk-8
    environment:
      DEBIAN_FRONTEND: "noninteractive"
    steps:
      - checkout
      - run: *install-xmlstarlet
      - restore_cache:
          key: dep-cache-{{ checksum "pom.xml" }}
      - run:
          name: Maven deploy
          command: mvn deploy -s .circleci/settings.xml
  trigger-dependants:
    docker:
      - image: ellerbrock/alpine-bash-curl-ssl
        cmd: ["/bin/bash"]
    steps:
      - trigger_others:
        name: "Trigger dependant jobs"
        command: |
          curl -u ${TIAMAT_API_TOKEN}: \
               -d build_parameters[CIRCLE_JOB]=deploy-docker \
               https://circleci.com/api/v1.1/project/github/entur/tiamat/tree/master
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build:
          context: org-carbon
      - deploy:
          context: org-carbon
          requires:
            - build
          filters:
            branches:
              only: master