version: 2
jobs:
  build:
    docker:
      - image: eu.gcr.io/carbon-1287/circleci-toolbox-image
        auth:
          username: _json_key
          password: $GCLOUD_SERVICE_KEY
    environment:
      MAVEN_OPTS: -Xmx3G
    steps:
      - checkout
      - restore_cache:
          key: dep-cache-{{ checksum "pom.xml" }}
      - run: mvn org.apache.maven.plugins:maven-dependency-plugin:3.1.0:go-offline -s /tools/m2/settings.xml
      - save_cache:
          paths:
            - ~/.m2
          key: dep-cache-{{ checksum "pom.xml" }}
      # Cannot use -o because of snapshot dependencies.
      - run: mvn install -s /tools/m2/settings.xml
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
  deploy:
    docker:
      - image: eu.gcr.io/carbon-1287/circleci-toolbox-image
        auth:
          username: _json_key
          password: $GCLOUD_SERVICE_KEY
    environment:
      DEBIAN_FRONTEND: "noninteractive"
    steps:
      - checkout
      - restore_cache:
          key: dep-cache-{{ checksum "pom.xml" }}
      - run:
          name: Maven deploy
          command: mvn deploy -s /tools/m2/settings.xml
  trigger-dependants:
    docker:
      - image: eu.gcr.io/carbon-1287/circleci-toolbox-image
        auth:
          username: _json_key
          password: $GCLOUD_SERVICE_KEY
    steps:
      - run:
          name: Trigger dependant builds
          command: |
            echo 'export CIRCLE_API_TOKEN="$CIRCLE_API_TOKEN"' >> $BASH_ENV
            /tools/downstream_single_trigger.sh "github/entur/tiamat" "master"
            /tools/downstream_single_trigger.sh "github/entur/anshar" "master"
            /tools/downstream_single_trigger.sh "github/entur/baba" "master"
            /tools/downstream_single_trigger.sh "github/entur/asag" "master"
            /tools/downstream_single_trigger.sh "github/entur/chouette" "master"
            /tools/downstream_single_trigger.sh "github/entur/extime" "master"
            /tools/downstream_single_trigger.sh "github/entur/kakka" "master"
            /tools/downstream_single_trigger.sh "github/entur/marduk" "master"
            /tools/downstream_single_trigger.sh "github/entur/namtar" "master"
            /tools/downstream_single_trigger.sh "github/entur/uttu" "master"
            /tools/downstream_single_trigger.sh "github/entur/opentripplanner" "rutebanken_develop"
            /tools/downstream_single_trigger.sh "github/entur/profile-norway-validation" "master"
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build:
          context: org-carbon
      - deploy:
          context: org-carbon
          requires:
            - build
          filters:
            branches:
              only: master
      - trigger-dependants:
          context: org-carbon
          requires:
            - deploy